default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: rating_app_development

test: &test
  <<: *default
  database: rating_app_test

production:
  <<: *default
  database: rating_app_production